<a href="https://colab.research.google.com/github/adharsh1904/CASESTUDY7/blob/main/casestudy7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

PART A

TASK1

In [ ]:
import pandas as pd

population = pd.read_csv("/content/drive/MyDrive/casestudy7/population.csv")

print(population.head())
print(population.shape)
print(population.dtypes)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525
(25, 2)
country       object
population     int64
dtype: object

TASK2

In [ ]:
import pandas as pd
import os

folder_path = "/content/drive/MyDrive/casestudy7/"
all_files = os.listdir(folder_path) if os.path.exists(folder_path) else []

# Look for a file with 'gdp' in its name dynamically
gdp_file = next((f for f in all_files if "gdp" in f.lower()), None)

if gdp_file:
    full_path = os.path.join(folder_path, gdp_file)
    print(f"Found GDP file: {gdp_file}")
    if gdp_file.endswith(".csv"):
        gdp = pd.read_csv(full_path)
    elif gdp_file.endswith(".json"):
        gdp = pd.read_json(full_path)
    elif gdp_file.endswith(".xml"):
        gdp = pd.read_xml(full_path)
    else:
        gdp = pd.read_excel(full_path)

    # Standardize column to 'country'
    if 'name' in gdp.columns:
        gdp.rename(columns={'name': 'country'}, inplace=True)
    elif 'Country' in gdp.columns:
        gdp.rename(columns={'Country': 'country'}, inplace=True)

    print("\n--- GDP Data Preview ---")
    print(gdp.head())
    print("Columns:", gdp.columns.tolist())
else:
    print("No specific 'gdp' file found in folder. Available files are:", all_files)

Found GDP file: gdp.xlsx

--- GDP Data Preview ---
         country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000
Columns: ['country', 'GDP']

TASK3

In [ ]:
import pandas as pd

internet_users = pd.read_json("/content/drive/MyDrive/casestudy7/internet_users.json")

print(internet_users.head())
print(internet_users.dtypes)

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000
country           object
internet_users     int64
dtype: object

TASK4

In [ ]:
import pandas as pd

literacy_rate = pd.read_xml("/content/drive/MyDrive/casestudy7/literacy_rate.xml")

print(literacy_rate.head())
print(literacy_rate.dtypes)

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0
name              object
literacy_rate    float64
dtype: object

PART:B
TASK5

In [ ]:
datasets = {
    "Population": population,
    "GDP": gdp,
    "Internet Users": internet_users,
    "Literacy Rate": literacy_rate
}

for name, data in datasets.items():
    print("\n========================")
    print(name)
    print("========================")
    print("Rows:", data.shape[0])
    print("Columns:", data.shape[1])
    print("Column Names:", data.columns.tolist())
    print("\nData Types:")
    print(data.dtypes)
    print("\nMissing Values:")
    print(data.isnull().sum())
    print("Duplicate Records:", data.duplicated().sum())

========================
Population
========================
Rows: 25
Columns: 2
Column Names: ['country', 'population']

Data Types:
country       object
population     int64
dtype: object

Missing Values:
country       0
population    0
dtype: int64
Duplicate Records: 0

========================
GDP
========================
Rows: 25
Columns: 2
Column Names: ['name', 'literacy_rate']

Data Types:
name              object
literacy_rate    float64
dtype: object

Missing Values:
name             0
literacy_rate    0
dtype: int64
Duplicate Records: 0

========================
Internet Users
========================
Rows: 25
Columns: 2
Column Names: ['country', 'internet_users']

Data Types:
country           object
internet_users     int64
dtype: object

Missing Values:
country           0
internet_users    0
dtype: int64
Duplicate Records: 0

========================
Literacy Rate
========================
Rows: 25
Columns: 2
Column Names: ['name', 'literacy_rate']

Data Types:
name              object
literacy_rate    float64
dtype: object

Missing Values:
name             0
literacy_rate    0
dtype: int64
Duplicate Records: 0

PART:C

TASK6

In [ ]:
gdp.rename(columns={"Country": "country"}, inplace=True)
literacy_rate.rename(columns={"name": "country"}, inplace=True)

TASK7

In [ ]:
population["population"] = pd.to_numeric(population["population"], errors="coerce")
if "GDP" in gdp.columns:
    gdp["GDP"] = pd.to_numeric(gdp["GDP"])
else:
    print("Warning: 'GDP' column not found in gdp DataFrame. Current columns are:", gdp.columns.tolist())

internet_users["internet_users"] = pd.to_numeric(internet_users["internet_users"])
literacy_rate["literacy_rate"] = pd.to_numeric(literacy_rate["literacy_rate"])

TASK8

In [ ]:
if 'name' in gdp.columns:
    gdp.rename(columns={'name': 'country'}, inplace=True)

df = population.merge(gdp, on="country") \
               .merge(internet_users, on="country") \
               .merge(literacy_rate, on="country")

print(df.head())

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

TASK9

In [ ]:
df["Internet Penetration (%)"] = (
    df["internet_users"] / df["population"] * 100
).round(2)

df["GDP Per Capita"] = (
    df["GDP"] * 1000000 / df["population"]
).round(2)

print(df.head())

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26        92144.28
1                     76.50        13621.11
2                     61.59         3034.05
3                     93.77        33217.83
4                     94.91        56991.47

PART:D

TASK10

In [ ]:
import sqlite3
conn = sqlite3.connect("country_statistics.db")
df.to_sql(
    "country_statistics",
    conn,
    if_exists="replace",
    index=False
)
print("Data loaded successfully")

Data loaded successfully

TASK11

In [ ]:
result = pd.read_sql(
    "SELECT * FROM country_statistics LIMIT 5",
    conn
)
print(result)

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26        92144.28
1                     76.50        13621.11
2                     61.59         3034.05
3                     93.77        33217.83
4                     94.91        56991.47

PART:E

1

In [ ]:
df.nlargest(5, "GDP")[["country", "GDP"]]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

2

In [ ]:
df.nlargest(5, "population")[["country", "population"]]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

3

In [ ]:
df["literacy_rate"].mean()

np.float64(97.248)

4

In [ ]:
df[df["literacy_rate"] > 90][["country", "literacy_rate"]]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

5

In [ ]:
df[df["Internet Penetration (%)"] > 70][
    ["country", "Internet Penetration (%)"]]

           country  Internet Penetration (%)
0    United States                     94.26
1            China                     76.50
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
10          Brazil                     85.15
11          Russia                     85.65
12     South Korea                     96.56
13           Spain                     94.11
14          Mexico                     79.11
15       Indonesia                     77.51
16    Saudi Arabia                     97.66
17          Turkey                     81.81
18    South Africa                     72.50
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

6

In [ ]:
df.nlargest(5, "GDP Per Capita")[
    ["country", "GDP Per Capita"]]

          country  GDP Per Capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66

7

In [ ]:
df["population"].sum()

np.int64(4720039725)

8

In [ ]:
df["Internet Penetration (%)"].mean()

np.float64(89.6596)

9

In [ ]:
df.loc[df["internet_users"].idxmax(), ["country", "internet_users"]]

country                China
internet_users    1080000000
Name: 1, dtype: object

10

In [ ]:
df["literacy_rate"].corr(
    df["Internet Penetration (%)"]
)

np.float64(0.77279756813985)